import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.scss";
import { Inter } from "next/font/google";
import Script from "next/script";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Alif | Blogs",
  description:
    "This is personal blog site of ashabul jannat alif. Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
        <Script src="https://smtpjs.com/v3/smtp.js"></Script>
      </body>
    </html>
  );
}
